services:
  - type: web
    name: sniper-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python btc_price_bot.py
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
